#lang racket
(define (measure name thunk)
  (define start (current-inexact-milliseconds))
  (thunk)
  (printf "~a: ~a ms\n" name (- (current-inexact-milliseconds) start)))

(measure "dotenv" (lambda () (dynamic-require "dotenv.rkt" #f)))
(measure "dspy-core" (lambda () (dynamic-require "dspy-core.rkt" #f)))
(measure "openai-responses-stream" (lambda () (dynamic-require "openai-responses-stream.rkt" #f)))
(measure "context-store" (lambda () (dynamic-require "context-store.rkt" #f)))
(measure "openai-client" (lambda () (dynamic-require "openai-client.rkt" #f)))
(measure "acp-tools" (lambda () (dynamic-require "acp-tools.rkt" #f)))
(measure "acp-stdio" (lambda () (dynamic-require "acp-stdio.rkt" #f)))
(measure "optimizer-gepa" (lambda () (dynamic-require "optimizer-gepa.rkt" #f)))
(measure "trace-store" (lambda () (dynamic-require "trace-store.rkt" #f)))
(measure "rdf-tools" (lambda () (dynamic-require "rdf-tools.rkt" #f)))
(measure "process-supervisor" (lambda () (dynamic-require "process-supervisor.rkt" #f)))
(measure "sandbox-exec" (lambda () (dynamic-require "sandbox-exec.rkt" #f)))
(measure "debug" (lambda () (dynamic-require "debug.rkt" #f)))
(measure "pricing-model" (lambda () (dynamic-require "pricing-model.rkt" #f)))
(measure "vector-store" (lambda () (dynamic-require "vector-store.rkt" #f)))
(measure "workflow-engine" (lambda () (dynamic-require "workflow-engine.rkt" #f)))
(measure "utils-time" (lambda () (dynamic-require "utils-time.rkt" #f)))
(measure "web-search" (lambda () (dynamic-require "web-search.rkt" #f)))
